reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resource :session
  resources :subs do
    resources :posts
  end
end

reddit_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reddit_clone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, presence: true
  validates :post_subs, presence: true
  
  belongs_to :author,
  foreign_key: :author_id,
  class_name: :User
  
  has_many :post_subs
  
  has_many :subs,
    through: :post_subs,
    source: :sub
end

reddit_clone/app/models/post_sub.rb
# == Schema Information
#
# Table name: post_subs
#
#  id         :integer          not null, primary key
#  sub_id     :integer          not null
#  post_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostSub < ApplicationRecord
  
  belongs_to :post
  belongs_to :sub

end

reddit_clone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :string           not null
#  mod_id      :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ApplicationRecord 
  validates :title, :description, :mod_id, presence: true
  
  belongs_to :moderator, 
    foreign_key: :mod_id,
    class_name: :User
  
  has_many :post_subs
  
  has_many :posts,
    through: :post_subs,
    source: :post
end 

reddit_clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  
  attr_reader :password
  after_initialize :ensure_session_token
  
  has_many :subs,
    foreign_key: :mod_id,
    class_name: :Sub
    
    has_many :posts,
    foreign_key: :author_id,
    class_name: :Post
  
  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user && user.is_password?(password)
    user
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end
  
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
end

reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def login(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end 
  
  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end 
  
  def logout 
    current_user.reset_session_token!
    session[:session_token] = nil
  end 
  
  def logged_in?
    !!current_user
  end 
  
  def require_login
    redirect_to new_session_url unless logged_in?
  end 
end

reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login
  
  def new
    @post = Post.new
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id 
    
    if @post.save
      redirect_to sub_url(@post.sub_id)
    else
      flash.now[:errors] = @post.errors.full_messages
      redirect_to sub_url(@post.sub_id)
    end
  end
  
  def update
    @post = Post.find(params[:id])
    
    if @post.update_attributes(post_params)
      redirect_to sub_posts_url
    else 
      flash.now[:errors] = ['Cannot Update']
      render :edit 
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to sub_posts_url
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def post_params
    params.require(:post).permit(:title, :url, :content)
  end
end

reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    
    if user
      login(user)
      redirect_to user_url(user)
    else
      flash.now[:errors] = ["Invalid password and/or username"]
      render :new
    end
  end
  
  def destroy
    logout
    redirect_to new_session_url
  end
end

reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  
  before_action :require_login, except: [:index, :show]
  
  def index 
    @subs = Sub.all
  end 
  
  def show 
    @sub = Sub.find(params[:id])
  end 
  
  def new 
    @sub = Sub.new
  end 
  
  def create 
    @sub = Sub.new(sub_params)
    @sub.mod_id = current_user.id
    
    if @sub.save
      redirect_to sub_url(@sub)
    else 
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end 
  end 
  
  def edit 
    @sub = Sub.find(params[:id])
  end 
  
  def update
    @sub = Sub.find(params[:id])
    
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = ["Could not update"]
      render :edit
    end
  end 
  
  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy 
    redirect_to subs_url
  end 
  
  private
  
  def sub_params 
    params.require(:sub).permit(:title, :description)
  end 
end

reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index 
    @users = User.all
  end 
  
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else 
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  def destroy
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user 
      @user.destroy
      redirect_to new_session_url
    else 
      flash[:errors] = ['Cannot find user']
      redirect_to users_url
    end 
  end 
  
  def edit 
    @user = User.find(params[:id])
  end 
  
  def update 
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_url(@user)
    else 
      flash.now[:errors] = ['Cannot update']
      render :edit
    end 
  end 
  
  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

reddit_clone/app/helpers/sessions_helper.rb
module SessionsHelper
end

reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

reddit_clone/app/helpers/users_helper.rb
module UsersHelper
end

reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
        <form action="<%= session_url %>" method="post">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <input type="hidden" name="_method" value="delete">
          <input type="submit" value="Sign Out">
        </form>
      <% else  %>
        <a href="<%= new_session_url %>">Sign In</a>
        <a href="<%= new_user_url %>">Sign Up</a>
    <% end %>
    
    <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
        <li><%= error %></li>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>

reddit_clone/app/views/posts/show.html.erb
<h2>Posts</h2>

<%= @post.title %>
<%= @post.url %>
<%= @post.content %>

reddit_clone/app/views/subs/edit.html.erb
<h2>Edit Sub</h2>

<form action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="patch">
  
  <label>
    Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
    </label>
  <label>
    Description
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
    </label>
  
    <input type="submit" value="Edit Sub">
</form>

reddit_clone/app/views/subs/index.html.erb
<% @subs.each do |sub| %>
  <ul>
    <li> <%= sub.title %> </li>
  </ul>


<% end %>

reddit_clone/app/views/subs/new.html.erb
<h2>Create New Sub</h2>

<form action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <label>
    Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
    </label>
  <label>
    Description
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
    </label>
  
    <input type="submit" value="Create New Sub">
</form>

reddit_clone/app/views/subs/show.html.erb
<h2><%= @sub.title %></h2>

<h3><%= @sub.description %></h3>

<a href="<%= edit_sub_url(@sub) %>">Edit Sub</a>

<form action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="Remove Sub">
</form>


<h4>Add Post</h4>
<form action="<%= sub_posts_url(@sub) %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    
    <label>
      Title
      <input type="text" name="post[title]" value="">
      </label>
    <label>
      Content
      <input type="text" name="post[content]" value="">
      </label>
    <label>
      URL
      <input type="text" name="post[url]" value="">
      </label>
      
      <input type="submit" value="Add Post">
</form>

<% @sub.posts.each do |post| %>
  <ul>
    Title: <%= post.title %>
  </ul>  
  <li>Content: <%= post.content %></li>
  <li>URL: <%= post.url %></li>

<% end %>

reddit_clone/app/views/users/edit.html.erb
<h2>Edit User</h2>

<form action="<%= user_url(@user)%> " method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="patch">
  
  <label>
    Username
    <input type="text" name="user[username]" value=" <%=@user.username %>">
  </label>
  
  <label>
    Password
    <input type="password" name="user[password]" value="">
  </label>
  
  <input type="submit" value="Edit User">
</form>

reddit_clone/app/views/users/index.html.erb
<h2>Users</h2>

<% @users.each do |user| %>
  <ul>
    <li><%= user.username %></li>
  </ul>

<% end %>

reddit_clone/app/views/users/new.html.erb
<h2>Sign Up</h2>

<form action="<%= users_url %>" method="post">
  <input type="hidden" 
    name="authenticity_token" 
    value="<%= form_authenticity_token %>">
    
    <label>
      Username
      <input type="text" name="user[username]" value="">
      </label>
      
    <label>
      Password
      <input type="password" name="user[password]" value="">
      </label>
      
      <input type="submit" value="Sign Up">
</form>

reddit_clone/app/views/users/show.html.erb
<h2><%= @user.username %></h2>

<a href="<%= edit_user_url(@user) %>">Edit User</a>